name: lsp_constructor_flow
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0-239.0.dev <3.0.0'

dependencies:
  lsp:
    git: git@github.com:ltOgt/lsp.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
